export let catImageList = [
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 16',
          metric: '3 - 7',
        },
        id: 'abob',
        name: 'American Bobtail',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/american-bobtail',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail',
        temperament: 'Intelligent, Interactive, Lively, Playful, Sensitive',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.',
        life_span: '11 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/American_Bobtail',
        hypoallergenic: 0,
        reference_image_id: 'hBXicehMA',
      },
    ],
    id: 'vH0bd0YDH',
    url: 'https://cdn2.thecatapi.com/images/vH0bd0YDH.jpg',
    width: 1335,
    height: 1206,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '4 - 10',
          metric: '2 - 5',
        },
        id: 'bali',
        name: 'Balinese',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Balinese.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/balinese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/balinese',
        temperament: 'Affectionate, Intelligent, Playful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
        life_span: '10 - 15',
        indoor: 0,
        alt_names: 'Long-haired Siamese',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Balinese_(cat)',
        hypoallergenic: 1,
        reference_image_id: '13MkvUreZ',
      },
    ],
    id: 'aU69p2mTT',
    url: 'https://cdn2.thecatapi.com/images/aU69p2mTT.jpg',
    width: 1024,
    height: 768,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 14',
          metric: '3 - 6',
        },
        id: 'esho',
        name: 'Exotic Shorthair',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/Exotic.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/exotic-shorthair',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/exotic-shorthair',
        temperament: 'Affectionate, Sweet, Loyal, Quiet, Peaceful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Exotic',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 3,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 2,
        social_needs: 4,
        stranger_friendly: 2,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Exotic_Shorthair',
        hypoallergenic: 0,
        reference_image_id: 'YnPrYEmfe',
      },
    ],
    id: 'dTlqinfQA',
    url: 'https://cdn2.thecatapi.com/images/dTlqinfQA.jpg',
    width: 4000,
    height: 3000,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '6 - 10',
          metric: '3 - 5',
        },
        id: 'hbro',
        name: 'Havana Brown',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/HavanaBrown.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/havana-brown',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/havana-brown',
        temperament:
          'Affectionate, Curious, Demanding, Friendly, Intelligent, Playful',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The Havana Brown is human oriented, playful, and curious. She has a strong desire to spend time with her people and involve herself in everything they do. Being naturally inquisitive, the Havana Brown reaches out with a paw to touch and feel when investigating curiosities in its environment. They are truly sensitive by nature and frequently gently touch their human companions as if they are extending a paw of friendship.',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Havana, HB',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Havana_Brown',
        hypoallergenic: 0,
        reference_image_id: 'njK25knLH',
      },
    ],
    id: '9JisqWsnL',
    url: 'https://cdn2.thecatapi.com/images/9JisqWsnL.jpg',
    width: 1024,
    height: 768,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 15',
          metric: '4 - 7',
        },
        id: 'chee',
        name: 'Cheetoh',
        temperament: 'Affectionate, Gentle, Intelligent, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Cheetoh has a super affectionate nature and real love for their human companions; they are intelligent with the ability to learn quickly. You can expect that a Cheetoh will be a fun-loving kitty who enjoys playing, running, and jumping through every room in your house.',
        life_span: '12 - 14',
        indoor: 0,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_cat#Cheetoh',
        hypoallergenic: 0,
        reference_image_id: 'IFXsxmXLm',
      },
    ],
    id: 'mNOdlAkXR',
    url: 'https://cdn2.thecatapi.com/images/mNOdlAkXR.jpg',
    width: 1280,
    height: 800,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 15',
          metric: '4 - 7',
        },
        id: 'chee',
        name: 'Cheetoh',
        temperament: 'Affectionate, Gentle, Intelligent, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Cheetoh has a super affectionate nature and real love for their human companions; they are intelligent with the ability to learn quickly. You can expect that a Cheetoh will be a fun-loving kitty who enjoys playing, running, and jumping through every room in your house.',
        life_span: '12 - 14',
        indoor: 0,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_cat#Cheetoh',
        hypoallergenic: 0,
        reference_image_id: 'IFXsxmXLm',
      },
    ],
    id: 'LX9uvE3dl',
    url: 'https://cdn2.thecatapi.com/images/LX9uvE3dl.jpg',
    width: 1919,
    height: 1919,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 14',
          metric: '3 - 6',
        },
        id: 'hima',
        name: 'Himalayan',
        vetstreet_url: 'http://www.vetstreet.com/cats/himalayan',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/himalayan',
        temperament: 'Dependent, Gentle, Intelligent, Quiet, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Calm and devoted, Himalayans make excellent companions, though they prefer a quieter home. They are playful in a sedate kind of way and enjoy having an assortment of toys. The Himalayan will stretch out next to you, sleep in your bed and even sit on your lap when she is in the mood.',
        life_span: '9 - 15',
        indoor: 0,
        lap: 1,
        alt_names:
          'Himalayan Persian, Colourpoint Persian, Longhaired Colourpoint, Himmy',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 2,
        dog_friendly: 2,
        energy_level: 1,
        grooming: 5,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 4,
        social_needs: 4,
        stranger_friendly: 2,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Himalayan_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'CDhOtM-Ig',
      },
    ],
    id: 'TdxQ2VvJK',
    url: 'https://cdn2.thecatapi.com/images/TdxQ2VvJK.jpg',
    width: 1280,
    height: 850,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '5 - 10',
          metric: '2 - 5',
        },
        id: 'java',
        name: 'Javanese',
        vetstreet_url: 'http://www.vetstreet.com/cats/javanese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/javanese',
        temperament: 'Active, Devoted, Intelligent, Playful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Javanese are endlessly interested, intelligent and active. They tend to enjoy jumping to great heights, playing with fishing pole-type or other interactive toys and just generally investigating their surroundings. He will attempt to copy things you do, such as opening doors or drawers.',
        life_span: '10 - 12',
        indoor: 0,
        alt_names: '',
        adaptability: 4,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Javanese_cat',
        hypoallergenic: 1,
        reference_image_id: 'xoI_EpOKe',
      },
    ],
    id: 'O1X8xKt_H',
    url: 'https://cdn2.thecatapi.com/images/O1X8xKt_H.jpg',
    width: 1800,
    height: 2700,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 13',
          metric: '3 - 6',
        },
        id: 'manx',
        name: 'Manx',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Manx.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/manx',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/manx',
        temperament: 'Easy Going, Intelligent, Loyal, Playful, Social',
        origin: 'Isle of Man',
        country_codes: 'IM',
        country_code: 'IM',
        description:
          'The Manx is a placid, sweet cat that is gentle and playful. She never seems to get too upset about anything. She is a loving companion and adores being with people.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Manks, Stubbin, Rumpy',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Manx_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'fhYh2PDcC',
      },
    ],
    id: 'AoDtRhYcL',
    url: 'https://cdn2.thecatapi.com/images/AoDtRhYcL.jpg',
    width: 1024,
    height: 683,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 13',
          metric: '3 - 6',
        },
        id: 'manx',
        name: 'Manx',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Manx.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/manx',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/manx',
        temperament: 'Easy Going, Intelligent, Loyal, Playful, Social',
        origin: 'Isle of Man',
        country_codes: 'IM',
        country_code: 'IM',
        description:
          'The Manx is a placid, sweet cat that is gentle and playful. She never seems to get too upset about anything. She is a loving companion and adores being with people.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Manks, Stubbin, Rumpy',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Manx_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'fhYh2PDcC',
      },
    ],
    id: 'OXMyfVPcP',
    url: 'https://cdn2.thecatapi.com/images/OXMyfVPcP.jpg',
    width: 1600,
    height: 1511,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '5 - 9',
          metric: '2 - 4',
        },
        id: 'munc',
        name: 'Munchkin',
        vetstreet_url: 'http://www.vetstreet.com/cats/munchkin',
        temperament: 'Agile, Easy Going, Intelligent, Playful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 2,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Munchkin_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'j5cVSqLer',
      },
    ],
    id: 'DZba-eH_4',
    url: 'https://cdn2.thecatapi.com/images/DZba-eH_4.jpg',
    width: 874,
    height: 1366,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 15',
          metric: '3 - 7',
        },
        id: 'ocic',
        name: 'Ocicat',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Ocicat.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/ocicat',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/ocicat',
        temperament:
          'Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          "Loyal and devoted to their owners, the Ocicat is intelligent, confident, outgoing, and seems to have many dog traits. They can be trained to fetch toys, walk on a lead, taught to 'speak', come when called, and follow other commands. ",
        life_span: '12 - 14',
        indoor: 0,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ocicat',
        hypoallergenic: 1,
        reference_image_id: 'JAx-08Y0n',
      },
    ],
    id: '_l8H9YK5_',
    url: 'https://cdn2.thecatapi.com/images/_l8H9YK5_.jpg',
    width: 1000,
    height: 750,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '12 - 20',
          metric: '5 - 9',
        },
        id: 'ragd',
        name: 'Ragdoll',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/ragdoll',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll',
        temperament: 'Affectionate, Friendly, Gentle, Quiet, Easygoing',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.',
        life_span: '12 - 17',
        indoor: 0,
        lap: 1,
        alt_names: 'Rag doll',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ragdoll',
        hypoallergenic: 0,
        reference_image_id: 'oGefY4YoG',
      },
    ],
    id: 'bju16uKfD',
    url: 'https://cdn2.thecatapi.com/images/bju16uKfD.jpg',
    width: 750,
    height: 871,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '5 - 11',
          metric: '2 - 5',
        },
        id: 'rblu',
        name: 'Russian Blue',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/RussianBlue.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/russian-blue-nebelung',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/russian-blue',
        temperament:
          'Active, Dependent, Easy Going, Gentle, Intelligent, Loyal, Playful, Quiet',
        origin: 'Russia',
        country_codes: 'RU',
        country_code: 'RU',
        description:
          'Russian Blues are very loving and reserved. They do not like noisy households but they do like to play and can be quite active when outdoors. They bond very closely with their owner and are known to be compatible with other pets.',
        life_span: '10 - 16',
        indoor: 0,
        lap: 1,
        alt_names: 'Archangel Blue, Archangel Cat',
        adaptability: 3,
        affection_level: 3,
        child_friendly: 3,
        dog_friendly: 3,
        energy_level: 3,
        grooming: 3,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 1,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Russian_Blue',
        hypoallergenic: 1,
        reference_image_id: 'Rhj-JsTLP',
      },
    ],
    id: 'tmH3RG7rD',
    url: 'https://cdn2.thecatapi.com/images/tmH3RG7rD.jpg',
    width: 3072,
    height: 2048,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '5 - 11',
          metric: '2 - 5',
        },
        id: 'sfol',
        name: 'Scottish Fold',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx',
        vetstreet_url:
          'http://www.vetstreet.com/cats/scottish-fold-highland-fold',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold',
        temperament:
          'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
        life_span: '11 - 14',
        indoor: 0,
        alt_names: 'Scot Fold',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 4,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Scottish_Fold',
        hypoallergenic: 0,
        reference_image_id: 'o9t0LDcsa',
      },
    ],
    id: 'IOqJ6RK7L',
    url: 'https://cdn2.thecatapi.com/images/IOqJ6RK7L.jpg',
    width: 750,
    height: 937,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '5 - 11',
          metric: '2 - 5',
        },
        id: 'sfol',
        name: 'Scottish Fold',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx',
        vetstreet_url:
          'http://www.vetstreet.com/cats/scottish-fold-highland-fold',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold',
        temperament:
          'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
        life_span: '11 - 14',
        indoor: 0,
        alt_names: 'Scot Fold',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 4,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Scottish_Fold',
        hypoallergenic: 0,
        reference_image_id: 'o9t0LDcsa',
      },
    ],
    id: 'wdT-_qOL3',
    url: 'https://cdn2.thecatapi.com/images/wdT-_qOL3.jpg',
    width: 2659,
    height: 1998,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 16',
          metric: '4 - 7',
        },
        id: 'sibe',
        name: 'Siberian',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Siberian.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/siberian',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/siberian',
        temperament:
          'Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate',
        origin: 'Russia',
        country_codes: 'RU',
        country_code: 'RU',
        description:
          'The Siberians dog like temperament and affection makes the ideal lap cat and will live quite happily indoors. Very agile and powerful, the Siberian cat can easily leap and reach high places, including the tops of refrigerators and even doors. ',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Moscow Semi-longhair, HairSiberian Forest Cat',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 2,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Siberian_(cat)',
        hypoallergenic: 1,
        reference_image_id: '3bkZAjRh1',
      },
    ],
    id: 'oxh-Aab7c',
    url: 'https://cdn2.thecatapi.com/images/oxh-Aab7c.jpg',
    width: 1066,
    height: 800,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 16',
          metric: '4 - 7',
        },
        id: 'cypr',
        name: 'Cyprus',
        temperament: 'Affectionate, Social',
        origin: 'Cyprus',
        country_codes: 'CY',
        country_code: 'CY',
        description:
          'Loving, loyal, social and inquisitive, the Cyprus cat forms strong ties with their families and love nothing more than to be involved in everything that goes on in their surroundings. They are not overly active by nature which makes them the perfect companion for people who would like to share their homes with a laid-back relaxed feline companion. ',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Cypriot cat',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 3,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Cyprus_cat',
        hypoallergenic: 0,
        reference_image_id: 'tJbzb7FKo',
      },
    ],
    id: 'cruhNBsv1',
    url: 'https://cdn2.thecatapi.com/images/cruhNBsv1.jpg',
    width: 1024,
    height: 768,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 14',
          metric: '3 - 6',
        },
        id: 'ebur',
        name: 'European Burmese',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/EuropeanBurmese.aspx',
        temperament: 'Sweet, Affectionate, Loyal',
        origin: 'Burma',
        country_codes: 'MM',
        country_code: 'MM',
        description:
          'The European Burmese is a very affectionate, intelligent, and loyal cat. They thrive on companionship and will want to be with you, participating in everything you do. While they might pick a favorite family member, chances are that they will interact with everyone in the home, as well as any visitors that come to call. They are inquisitive and playful, even as adults. ',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        cat_friendly: 4,
        dog_friendly: 4,
        energy_level: 4,
        grooming: 1,
        health_issues: 4,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 4,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        hypoallergenic: 0,
      },
    ],
    id: 'd8sbdRtLJ',
    url: 'https://cdn2.thecatapi.com/images/d8sbdRtLJ.jpg',
    width: 1050,
    height: 1126,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '12 - 18',
          metric: '5 - 8',
        },
        id: 'ycho',
        name: 'York Chocolate',
        temperament: 'Playful, Social, Intelligent, Curious, Friendly',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          "York Chocolate cats are known to be true lap cats with a sweet temperament. They love to be cuddled and petted. Their curious nature makes them follow you all the time and participate in almost everything you do, even if it's related to water: unlike many other cats, York Chocolates love it.",
        life_span: '13 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'York',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 4,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/York_Chocolate',
        hypoallergenic: 0,
        reference_image_id: '0SxW2SQ_S',
      },
    ],
    id: 'sNSYauLG8',
    url: 'https://cdn2.thecatapi.com/images/sNSYauLG8.jpg',
    width: 1080,
    height: 1350,
  },
];

export let dogImageList = [
  {
    breeds: [
      {
        weight: {
          imperial: '7 - 10',
          metric: '3 - 5',
        },
        height: {
          imperial: '9 - 12',
          metric: '23 - 30',
        },
        id: 13,
        name: 'American Eskimo Dog (Miniature)',
        country_code: 'US',
        bred_for: 'Companionship',
        life_span: '13 – 15 years',
        temperament: 'Friendly, Alert, Reserved, Intelligent, Protective',
        reference_image_id: '_gn8GLrE6',
      },
    ],
    id: 'HJq5ke5Nm',
    url: 'https://cdn2.thedogapi.com/images/HJq5ke5Nm_1280.jpg',
    width: 1754,
    height: 1168,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '50 - 60',
          metric: '23 - 27',
        },
        height: {
          imperial: '17 - 19',
          metric: '43 - 48',
        },
        id: 16,
        name: 'American Staffordshire Terrier',
        country_code: 'US',
        bred_for: '',
        breed_group: 'Terrier',
        life_span: '12 - 15 years',
        temperament:
          'Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous',
        reference_image_id: 'rJIakgc4m',
      },
    ],
    id: 'rJIakgc4m',
    url: 'https://cdn2.thedogapi.com/images/rJIakgc4m_1280.jpg',
    width: 357,
    height: 500,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '65 - 100',
          metric: '29 - 45',
        },
        height: {
          imperial: '23 - 27',
          metric: '58 - 69',
        },
        id: 43,
        name: 'Black and Tan Coonhound',
        bred_for: 'Hunting raccoons, night hunting',
        breed_group: 'Hound',
        life_span: '10 - 12 years',
        temperament:
          'Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable',
        reference_image_id: 'HJAFgxcNQ',
      },
    ],
    id: 'HJAFgxcNQ',
    url: 'https://cdn2.thedogapi.com/images/HJAFgxcNQ_1280.jpg',
    width: 556,
    height: 380,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '9 - 15',
          metric: '4 - 7',
        },
        height: {
          imperial: '9 - 11',
          metric: '23 - 28',
        },
        id: 89,
        name: 'Coton de Tulear',
        bred_for:
          'Accompanying ladies on long sea voyages, ratters onboard ship.',
        breed_group: 'Non-Sporting',
        life_span: '13 - 16 years',
        temperament:
          'Affectionate, Lively, Playful, Intelligent, Trainable, Vocal',
        reference_image_id: 'SyviZlqNm',
      },
    ],
    id: 'SyviZlqNm',
    url: 'https://cdn2.thedogapi.com/images/SyviZlqNm_1280.jpg',
    width: 2464,
    height: 1638,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 14',
          metric: '4 - 6',
        },
        height: {
          imperial: '10',
          metric: '25',
        },
        id: 104,
        name: 'English Toy Spaniel',
        bred_for: 'Companion of kings',
        breed_group: 'Toy',
        life_span: '10 - 12 years',
        temperament: 'Affectionate, Reserved, Playful, Gentle, Happy, Loving',
        reference_image_id: 'SkIgzxqNQ',
      },
    ],
    id: 'SkIgzxqNQ',
    url: 'https://cdn2.thedogapi.com/images/SkIgzxqNQ_1280.jpg',
    width: 800,
    height: 696,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '28',
          metric: '13',
        },
        height: {
          imperial: '11 - 12',
          metric: '28 - 30',
        },
        id: 113,
        name: 'French Bulldog',
        bred_for: 'Lapdog',
        breed_group: 'Non-Sporting',
        life_span: '9 - 11 years',
        temperament:
          'Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright',
        reference_image_id: 'HyWNfxc47',
      },
    ],
    id: 'HyWNfxc47',
    url: 'https://cdn2.thedogapi.com/images/HyWNfxc47_1280.jpg',
    width: 740,
    height: 430,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '120 - 170',
          metric: '54 - 77',
        },
        height: {
          imperial: '25.5 - 31.5',
          metric: '65 - 80',
        },
        id: 155,
        name: 'Leonberger',
        bred_for: 'Guardian, appearance.',
        breed_group: 'Working',
        life_span: '6 - 8 years',
        temperament:
          'Obedient, Fearless, Loyal, Companionable, Adaptable, Loving',
        reference_image_id: 'ByrmQlqVm',
      },
    ],
    id: 'ByrmQlqVm',
    url: 'https://cdn2.thedogapi.com/images/ByrmQlqVm_1280.jpg',
    width: 1024,
    height: 694,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 25',
          metric: '4 - 11',
        },
        height: {
          imperial: '10 - 13',
          metric: '25 - 33',
        },
        id: 207,
        name: 'Rat Terrier',
        breed_group: 'Terrier',
        life_span: '12 - 18 years',
        temperament:
          'Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving',
        reference_image_id: 'HkXWNl9E7',
      },
    ],
    id: 'HkXWNl9E7',
    url: 'https://cdn2.thedogapi.com/images/HkXWNl9E7_1280.jpg',
    width: 825,
    height: 689,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '50 - 60',
          metric: '23 - 27',
        },
        height: {
          imperial: '19 - 23.5',
          metric: '48 - 60',
        },
        id: 214,
        name: 'Samoyed',
        bred_for: 'Herding reindeer, guardian, draft',
        breed_group: 'Working',
        life_span: '12 - 14 years',
        temperament: 'Stubborn, Friendly, Sociable, Lively, Alert, Playful',
        reference_image_id: 'S1T8Ee9Nm',
      },
    ],
    id: 'S1T8Ee9Nm',
    url: 'https://cdn2.thedogapi.com/images/S1T8Ee9Nm_1280.jpg',
    width: 1200,
    height: 797,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '85 - 140',
          metric: '39 - 64',
        },
        height: {
          imperial: '24 - 26',
          metric: '61 - 66',
        },
        id: 244,
        name: 'Tibetan Mastiff',
        breed_group: 'Working',
        life_span: '10 - 14 years',
        temperament:
          'Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective',
        reference_image_id: 'SkM9sec47',
      },
    ],
    id: 'SkM9sec47',
    url: 'https://cdn2.thedogapi.com/images/SkM9sec47_1280.jpg',
    width: 1600,
    height: 1375,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '45 - 70',
          metric: '20 - 32',
        },
        height: {
          imperial: '20 - 24',
          metric: '51 - 61',
        },
        id: 260,
        name: 'Wirehaired Pointing Griffon',
        bred_for:
          'Gundog, "swamp-tromping", Flushing, pointing, and retrieving water fowl & game birds',
        breed_group: 'Sporting',
        life_span: '12 - 14 years',
        temperament: 'Loyal, Gentle, Vigilant, Trainable, Proud',
        reference_image_id: 'Bkam2l9Vm',
      },
    ],
    id: 'Bkam2l9Vm',
    url: 'https://cdn2.thedogapi.com/images/Bkam2l9Vm_1280.jpg',
    width: 2328,
    height: 1604,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '30 - 150',
          metric: '14 - 68',
        },
        height: {
          imperial: '14 - 17',
          metric: '36 - 43',
        },
        id: 11,
        name: 'American Bully',
        country_code: 'US',
        bred_for: 'Family companion dog',
        breed_group: '',
        life_span: '8 – 15 years',
        temperament:
          'Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',
        reference_image_id: 'sqQJDtbpY',
      },
    ],
    id: 'sqQJDtbpY',
    url: 'https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg',
    width: 1024,
    height: 683,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '38 - 50',
          metric: '17 - 23',
        },
        height: {
          imperial: '23 - 26',
          metric: '58 - 66',
        },
        id: 8,
        name: 'Alaskan Husky',
        bred_for: 'Sled pulling',
        breed_group: 'Mixed',
        life_span: '10 - 13 years',
        temperament: 'Friendly, Energetic, Loyal, Gentle, Confident',
        reference_image_id: '-HgpNnGXl',
      },
    ],
    id: 'Nk8cSr_aj',
    url: 'https://cdn2.thedogapi.com/images/Nk8cSr_aj.jpg',
    width: 1350,
    height: 869,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '45 - 55',
          metric: '20 - 25',
        },
        height: {
          imperial: '20 - 22',
          metric: '51 - 56',
        },
        id: 32,
        name: 'Bearded Collie',
        bred_for: 'Sheep herding',
        breed_group: 'Herding',
        life_span: '12 - 14 years',
        temperament:
          'Self-confidence, Hardy, Lively, Alert, Intelligent, Active',
        reference_image_id: 'A09F4c1qP',
      },
    ],
    id: 'yxsOLj-GU',
    url: 'https://cdn2.thedogapi.com/images/yxsOLj-GU.jpg',
    width: 1080,
    height: 1319,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '50 - 70',
          metric: '23 - 32',
        },
        height: {
          imperial: '21 - 22',
          metric: '53 - 56',
        },
        id: 61,
        name: 'Bull Terrier',
        bred_for: 'Bull baiting, Fighting',
        breed_group: 'Terrier',
        life_span: '10 - 12 years',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active',
        reference_image_id: 'VSraIEQGd',
      },
    ],
    id: 'xNHN6Vu1e',
    url: 'https://cdn2.thedogapi.com/images/xNHN6Vu1e.jpg',
    width: 959,
    height: 958,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '50 - 70',
          metric: '23 - 32',
        },
        height: {
          imperial: '21 - 22',
          metric: '53 - 56',
        },
        id: 61,
        name: 'Bull Terrier',
        bred_for: 'Bull baiting, Fighting',
        breed_group: 'Terrier',
        life_span: '10 - 12 years',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active',
        reference_image_id: 'VSraIEQGd',
      },
    ],
    id: 'VSraIEQGd',
    url: 'https://cdn2.thedogapi.com/images/VSraIEQGd.jpg',
    width: 1080,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '20 - 30',
          metric: '9 - 14',
        },
        height: {
          imperial: '14 - 15',
          metric: '36 - 38',
        },
        id: 86,
        name: 'Cocker Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament:
          'Trainable, Friendly, Affectionate, Playful, Quiet, Faithful',
        reference_image_id: '1lFmrzECl',
      },
    ],
    id: 'BP9tUfS_h',
    url: 'https://cdn2.thedogapi.com/images/BP9tUfS_h.jpg',
    width: 1080,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '20 - 30',
          metric: '9 - 14',
        },
        height: {
          imperial: '14 - 15',
          metric: '36 - 38',
        },
        id: 86,
        name: 'Cocker Spaniel',
        bred_for: 'Bird flushing, retrieving',
        breed_group: 'Sporting',
        life_span: '12 - 15 years',
        temperament:
          'Trainable, Friendly, Affectionate, Playful, Quiet, Faithful',
        reference_image_id: '1lFmrzECl',
      },
    ],
    id: 'gW4R5SWbV',
    url: 'https://cdn2.thedogapi.com/images/gW4R5SWbV.jpg',
    width: 1080,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '20 - 24',
          metric: '9 - 11',
        },
        height: {
          imperial: '14 - 17',
          metric: '36 - 43',
        },
        id: 246,
        name: 'Tibetan Terrier',
        bred_for:
          'Good luck charms, mascots, watchdogs, herding dogs, and companions',
        breed_group: 'Non-Sporting',
        life_span: '12 - 15 years',
        temperament:
          'Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive',
        reference_image_id: '6f5n_42mB',
      },
    ],
    id: 'wRP-CQQJy',
    url: 'https://cdn2.thedogapi.com/images/wRP-CQQJy.jpg',
    width: 1080,
    height: 1308,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '30 - 50',
          metric: '14 - 23',
        },
        height: {
          imperial: '17.5 - 19.5',
          metric: '44 - 50',
        },
        id: 239,
        name: 'Standard Schnauzer',
        bred_for: 'Ratting, guarding',
        breed_group: 'Working',
        life_span: '13 - 15 years',
        temperament:
          'Trainable, Good-natured, Devoted, Lively, Playful, Intelligent',
        reference_image_id: 'tmzeu6ID_',
      },
    ],
    id: 'XLVd7vTZw',
    url: 'https://cdn2.thedogapi.com/images/XLVd7vTZw.jpg',
    width: 1280,
    height: 853,
  },
];
